### ISSUE TITLE
Image descriptions

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#539] opened 2022-04-16 03:46 UTC
- Not something most users would notice, but this page is not fully ADA compliant.  It's difficult to do programatically, but the alt text needs to describe what the image itself is about, not what the context of a link click is e.g. "Starbucks store sign with trees" as opposed to "Is Starbucks changing its baristas?".  I also don't see anything for the icons below each entry (but I"m not at a full laptop so I can't quite inspect and see)

Issue from Joshua Lugo

**Comment by lmcnulty** [comment] 2022-07-15 19:08
My first thought was that we could improve on the web-scraping to try and get the alt-text used in the articles, but in every one I've looked at, the alt-text was either missing or just a duplicate of the title 😞

I think most of the report images are purely decorative and would most appropriately just have `alt=""`, which makes screen readers ignore them. However, there are a few that add important information, like the ones for [Incident 53](https://incidentdatabase.ai/cite/53). Perhaps we could add a field on the submission form for the submitter to provide alt-text?

**Comment by smcgregor** [comment] 2022-11-30 18:29
I think we should set the alt text to empty since even in the case of Incident 53 the image doesn't add any insight beyond what is presented within the text of the report.

**Closed** 2023-01-25 14:24 UTC
