### ISSUE TITLE
Bug – Incident Table edit

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1147] opened 2022-09-24 10:22 UTC
Occurred when changing the incident metadata for `incident 310`.

<img width="946" alt="Screen Shot 2022-09-24 at 5 21 18 PM" src="https://user-images.githubusercontent.com/39468345/192092808-1ebd72b1-0d00-4ecc-9cac-6b000b68b4d7.png">

**Comment by smcgregor** [comment] 2022-09-24 17:19
Confirmed. I would guess this is happening because we just hooked the production server into the embedding cron jobs that runs via nlp-lambdas and nlp-monitoring. I believe _all_ incident editing on production will be broken at the moment. We likely need to edit the database schema definition and ensure these forms handle the new hidden fields properly.

**Comment by smcgregor** [comment] 2022-09-24 17:20
@lmcnulty I assigned you to the issue since I think you will know what is happening here, @cesarvarela is on here as secondary.

**Comment by lmcnulty** [comment] 2022-09-24 20:31
I don't think there's an issue with the schema – I was getting this in my dev environment. It was a result of the GraphQL query including a `__typename` field in the embedding object that has to be stripped on updating an incident. I don't believe the `IncidentEditModal` should ever change the embedding, so I'm just setting it to `undefined` in the handler.

I think we need more tests for the `IncidentEditModal`, since this should have been caught earlier. I'll open an issue for it.

I'll also note that the embedding was only involved here in the first place because we fetch the incident data with the GraphQL query in `site/gatsby-site/src/graphql/incidents.js`, which includes every field. My understanding is that the point of GraphQL is to allow you to request only the fields you need. I'm wondering if we should move towards using more limited queries where possible.

**Comment by smcgregor** [comment] 2022-09-24 21:58
@lmcnulty I am still seeing the problem in production. The form will load, but the console shows:
```
SemanticallyRelatedIncidents.js:112 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'embedding')
    at SemanticallyRelatedIncidents.js:112:65
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
```
Then when I try to save the form the toast with the error pops up and the graphql response is as below. I think the problem is that while you updated the modal form, this is not a modal form: https://incidentdatabase.ai/incidents/edit/?incident_id=333

Does that make sense?

`{"data":null,"errors":[{"message":"Variable \"$set\" got invalid value {\"AllegedDeployerOfAISystem\":[\"Tesla\"],\"AllegedDeveloperOfAISystem\":[\"Tesla\"],\"AllegedHarmedOrNearlyHarmedParties\":[\"unnamed 22-year-old male driver\",\"Tesla drivers\"],\"date\":\"2021-03-17\",\"description\":\"A Tesla Model Y on Autopilot collided with a parked Michigan State Police (MSP) car which had its emergency lights on, in Eaton County, Michigan, although no one was injured.\",\"editor_dissimilar_incidents\":[],\"editor_similar_incidents\":[],\"editors\":[\"Khoa Lam\"],\"embedding\":{\"__typename\":\"IncidentEmbedding\",\"from_reports\":[2045],\"vector\":[-0.11474460363388062,0.06590204685926437,-0.00302032008767128,-0.10306376963853836,0.09213942289352417,-0.01751602627336979,0.0003197263868059963,0.02947898954153061,0.030428126454353333,-0.16063767671585083,-0.030576355755329132,0.08732599765062332,0.03276839479804039,-0.11396092176437378,0.04737116023898125,-0.08120209723711014,-0.07278987765312195,-0.03639523684978485,0.013719282113015652,-0.112276591360569,-0.07504627108573914,-0.041646599769592285,0.053017519414424896,0.10306809097528458,-0.04556185379624367,0.02918284758925438,0.05887323617935181,0.12925536930561066,-0.05793130025267601,0.09934266656637192,-0.032316748052835464,-0.034619737416505814,0.12650324404239655,-0.01468275859951973,0.004122127313166857,0.10012955218553543,0.03764141723513603,-0.032441314309835434,-0.11624770611524582,0.0022842222824692726,0.04809080436825752,0.2354775071144104,-0.02015596441924572,-0.017533469945192337,0.033086176961660385,-0.0481831319630146,0.021941052749753,0.032952308654785156,0.01642332226037979,0.043442875146865845,-0.00784245040267706,-0.0002574087993707508,-0.030309496447443962,0.005469165742397308,-0.10950932651758194,0.08726835250854492,0.03980559483170509,0.009590848349034786,0.04163132980465889,-0.07423999905586243,-0.07599809020757675,-0.23761457204818726,-0.03896820545196533,-0.07538322359323502,0.08635389059782028,-0.08656249940395355,-0.02501673437654972,0.01946236751973629,0.055709898471832275,0.07566466927528381,0.08378946036100388,-0.09299056231975555,-0.041175827383995056,0.02119734324514866,0.012874369509518147,0.0052339304238557816,-0.003353622043505311,0.14697444438934326,-0.12268929928541183,0.007667417638003826,0.11300893872976303,-0.08934548497200012,0.47995448112487793,0.02857082150876522,-0.06184997037053108,-0.024426691234111786,0.09190234541893005,0.04383891448378563,0.029316259548068047,0.07267124205827713,-0.02698003686964512,-0.016140827909111977,-0.022127732634544373,0.07231133431196213,0.09470833092927933,0.0724724680185318,-0.009555687196552753,0.04501483961939812,-0.01620212011039257,-0.05341162905097008,0.012578198686242104,-0.05980132147669792,0.10302313417196274,0.023013288155198097,-0.03457846865057945,0.015125732868909836,0.0837465450167656,-0.008752909488976002,0.053327035158872604,-0.05181533843278885,0.04615259915590286,0.05136480927467346,0.07063606381416321,0.03236924111843109,0.05233036354184151,-0.03324037045240402,0.012775804847478867,0.02111293561756611,0.08284905552864075,-0.00399492122232914,-0.04182402789592743,0.04894571751356125,0.10289593040943146,-0.03688748553395271,-0.03517180681228638,-0.05277686566114426,-0.07267792522907257,-0.011781805194914341,-0.052928630262613297,0.01971295103430748,-0.048319749534130096,-0.2198522537946701,-0.0007348497165367007,0.0877867117524147,0.01127756666392088,-0.02109399624168873,-0.007328798528760672,-0.09058474749326706,0.014667903073132038,-0.020402222871780396,-0.024619750678539276,0.04649605229496956,0.06648623198270798,0.043499648571014404,0.0974622592329979,0.07903875410556793,-0.05188767611980438,-0.06173710152506828,0.00020848562417086214,-0.03301280736923218,0.062091171741485596,-0.10710855573415756,-0.04987499862909317,0.0371563546359539,0.03494637459516525,0.6993640661239624,0.14583127200603485,0.18789361417293549,0.0048516299575567245,-0.04367932677268982,0.1626216471195221,-0.01737476885318756,0.0335676409304142,-0.041549164801836014,-0.08492405712604523,0.017494402825832367,-0.05308324471116066,-0.04627849534153938,0.05648433417081833,0.06394632160663605,0.13835377991199493,0.042249683290719986,0.09400815516710281,0.013864945620298386,-0.13978612422943115,-0.04440029710531235,0.05918799713253975,0.017837902531027794,-0.0876779556274414,-0.027189457789063454,0.05627565458416939,0.09809748083353043,-0.0652943104505539,0.011404289864003658,-0.03975920379161835,0.039102938026189804,-0.014877203851938248,0.04247367009520531,-0.04284077137708664,0.02032824046909809,0.040866393595933914,0.08689403533935547,-0.016518937423825264,-0.12646694481372833,-0.049136705696582794,0.09618192166090012,0.011059681884944439,-0.03414278104901314,0.04355642572045326,-0.0858626514673233,0.042769186198711395,-0.016290955245494843,0.13953092694282532,-0.10558981448411942,0.04143470898270607,0.016437020152807236,0.028392847627401352,0.07964026927947998,-0.032629698514938354,-0.07632752507925034,-0.04227552190423012,0.05544912815093994,0.054885536432266235,0.0997261181473732,0.11512789875268936,-0.03074723482131958,0.050056688487529755,0.06560911238193512,-0.012477525509893894,-0.01345207542181015,0.0464194230735302,0.08410346508026123,-0.02354728803038597,-0.009889423847198486,0.04118305444717407,0.017000140622258186,0.06859532743692398,0.0011756540043279529,0.060214538127183914,-0.0007768351351842284,-0.03683614730834961,0.05562012642621994,0.022328052669763565,0.010857579298317432,0.13615664839744568,-0.05226794630289078,-0.05919581279158592,0.0005892134504392743,-0.029300212860107422,-0.02609974332153797,-0.042442429810762405,0.10819058865308762,0.057381290942430496,0.11336642503738403,0.0461665540933609,0.04025333747267723,0.048091478645801544,0.06610208004713058,0.04792485013604164,0.039244089275598526,-0.050547197461128235,-0.09702838957309723,-0.011081741191446781,0.0031387130729854107,0.0901021957397461,0.012558946385979652,-0.05890948325395584,-0.02162758819758892,-0.011907827109098434,-0.032837022095918655,-0.10841201990842819,-0.04638143256306648,0.006612901575863361,0.08983117341995239,-0.04918044060468674,-0.051907360553741455,-0.09937265515327454,0.00834001787006855,0.04350024089217186,0.01736089587211609,-0.010312729515135288,-0.11552830785512924,-0.060661450028419495,-0.018569692969322205,0.028530893847346306,0.0004353414406068623,-0.030247202143073082,-0.005108663812279701,-0.08143916726112366,-0.010921841487288475,-0.012975653633475304,-0.052180156111717224,-0.05203438550233841,-0.07113566994667053,-0.06383515149354935,0.026920998468995094,0.032574743032455444,-0.02469184249639511,0.04723126441240311,0.035399340093135834,0.03888530284166336,-0.050912290811538696,-0.02029612846672535,0.06527844816446304,-0.05260547995567322,-0.00793556496500969,0.06253736466169357,-0.0014481054386124015,0.06314614415168762,-0.005192209500819445,-0.05902599170804024,-0.016512008383870125,-0.011014368385076523,-0.06067966669797897,0.02558753825724125,-0.0328507125377655,-0.0037434841506183147,-0.030582211911678314,0.026729635894298553,0.07552198320627213,-0.08662774413824081,-0.06144446134567261,-0.11951134353876114,0.11863517016172409,0.020547546446323395,0.008075332269072533,0.016556229442358017,-0.04863540828227997,0.04229447618126869,-0.010945101268589497,0.0033932167571038008,0.06513132154941559,0.03503457084298134,-0.013700543902814388,-0.006728494539856911,0.04007481411099434,-0.028902830556035042,0.0219369325786829,0.061135608702898026,0.38355323672294617,-0.13378630578517914,0.054389581084251404,0.08388350903987885,0.0160263329744339,0.06589089334011078,-0.0653998851776123,0.08528106659650803,0.05972324684262276,0.10815387219190598,0.11528058350086212,-0.0034818786662071943,0.026020120829343796,-0.05369725450873375,0.0865403264760971,0.023970214650034904,0.003053126158192754,-0.021541902795433998,-0.09409588575363159,-0.015925681218504906,0.03763825073838234,-0.04324192553758621,-0.012894618324935436,-0.011020811274647713,-0.06521011143922806,-0.012016497552394867,0.038400765508413315,0.01849425584077835,-0.05946053937077522,0.0005291955312713981,-0.026615019887685776,0.026112813502550125,0.005859585478901863,0.04321777820587158,-0.11588302254676819,0.0624612458050251,-0.08792929351329803,-0.0688934251666069,0.09033104032278061,-0.004959860350936651,0.03380643203854561,0.04494763910770416,-0.01357326004654169,0.0020604878664016724,-0.028206128627061844,-0.06851393729448318,0.017511460930109024,0.0628482848405838,0.0013980285730212927,0.07995744049549103,0.16347254812717438,-0.03286483511328697,-0.04499491676688194,-0.05978328734636307,0.09078868478536606,0.10041916370391846,-0.05480731278657913,-0.0038170258048921824,-0.07506505399942398,-0.032366953790187836,-0.008858083747327328,-0.08246784657239914,-0.06752936542034149,0.018889376893639565,-0.05943267047405243,0.05983990430831909,-0.004628280643373728,-0.046690456569194794,-0.1719818115234375,0.005150436423718929,-0.03608744964003563,0.009751400910317898,0.12948596477508545,-0.05504864826798439,0.013316703028976917,0.05756918340921402,-0.026656359434127808,0.0001205569933517836,-0.102482371032238,0.027425583451986313,-0.08038187772035599,0.05640295147895813,0.010740535333752632,0.06785125285387039,-0.09588330239057541,0.04095672816038132,-0.09306390583515167,0.04573633894324303,0.045743655413389206,0.03504626825451851,0.02466885931789875,-0.03571592643857002,0.010464916005730629,0.017338307574391365,-0.024447107687592506,-0.010589423589408398,-0.07148796319961548,-0.025364818051457405,-0.0865204781293869,-0.04669972509145737,-0.013194147497415543,-0.04527093470096588,0.10380518436431885,-0.1082867905497551,-0.04226670041680336,-0.039952464401721954,-0.02202313020825386,0.025931604206562042,0.0631563812494278,0.022345850244164467,-0.15983419120311737,0.01982605829834938,-0.015101787634193897,0.09070691466331482,-0.029175207018852234,-0.05030526593327522,-0.007639986462891102,0.1447397619485855,0.05045950785279274,-0.0011620274744927883,-0.04467126354575157,-0.03756466135382652,-0.0029179230332374573,-0.06241269037127495,-0.532669723033905,0.026757214218378067,0.005966713652014732,0.0446263886988163,-0.0010327703785151243,-0.059232842177152634,0.0036165190394967794,-0.02780161425471306,-0.04565798491239548,0.07731883972883224,-0.055204473435878754,0.0006226436817087233,0.013496175408363342,-0.05295443907380104,-0.035323310643434525,-0.07018611580133438,-0.04956693947315216,0.04214267432689667,-0.05669169872999191,-0.06852515786886215,-0.09249912947416306,0.050711557269096375,-0.012639912776648998,-0.004166540689766407,-0.010450344532728195,0.025901181623339653,-0.11799630522727966,-0.05017973482608795,0.01663261651992798,0.08860837668180466,0.03880651295185089,-0.07928316295146942,-0.04651070013642311,0.0499422512948513,-0.047922614961862564,0.16229009628295898,0.03284600377082825,0.021414684131741524,-0.04494517296552658,0.07985176891088486,0.05078420042991638,0.1870483160018921,-0.011198938824236393,0.05374995246529579,0.03674393147230148,0.16573669016361237,0.0021825521253049374,0.03251054883003235,-0.017505589872598648,-0.0013483071234077215,0.009398778900504112,-0.014631266705691814,0.043935686349868774,-0.06435409188270569,-0.04451794922351837,-0.022596336901187897,-0.005620940588414669,-0.009504259563982487,-0.009087640792131424,0.1915494203567505,0.011181327514350414,0.02474335953593254,0.01561964862048626,-0.05328282713890076,-0.018743788823485374,-0.03237404301762581,-0.11715415120124817,-0.0062249284237623215,-0.018426574766635895,0.0013488249387592077,-0.05344449356198311,-0.12395138293504715,-0.007227913476526737,-0.034671928733587265,0.0006362767308019102,0.13666598498821259,-0.0005902671837247908,0.03959408402442932,-0.024745997041463852,0.12761346995830536,0.036440372467041016,0.021505337208509445,0.0848211869597435,0.10801225155591965,-0.0069116572849452496,-0.01442720741033554,-0.019091852009296417,-0.04995086416602135,-0.007694673724472523,0.0917118564248085,-0.07222781330347061,0.0686158761382103,0.041885796934366226,-0.040398627519607544,-0.06118512898683548,0.030447587370872498,-0.022526904940605164,0.05211056023836136,-0.47504204511642456,-0.0351167730987072,0.10228868573904037,0.026969678699970245,0.04466160014271736,0.06386120617389679,0.06646177172660828,-0.021203605458140373,-0.04089004546403885,-0.047537241131067276,0.12801653146743774,0.0033344486728310585,0.07649436593055725,-0.12603963911533356,0.05100720375776291,0.11830388754606247,-0.010737866163253784,-0.000773762003518641,0.04461238905787468,-0.1533581018447876,-0.012770463712513447,-0.04356083646416664,0.15169718861579895,0.05333523824810982,0.02188468724489212,0.047523897141218185,-0.06750448048114777,0.042255107313394547,0.033937402069568634,0.013926088809967041,0.08859068155288696,-0.0037757304962724447,-0.04804234579205513,0.12286905199289322,0.06440548598766327,0.11787370592355728,-0.008788058534264565,11.913905143737793,0.07826688140630722,0.03874695673584938,-0.06978508830070496,0.06337568163871765,-0.05867872014641762,0.015856802463531494,-0.1391158401966095,0.08961854875087738,0.1317289173603058,-0.02065412700176239,-0.016056831926107407,-0.04657154530286789,-0.08206076920032501,-0.011208037845790386,-0.050861358642578125,-0.05530845746397972,-0.02405904047191143,0.0035682811867445707,-0.04633291810750961,0.01778056100010872,0.015941202640533447,0.08289461582899094,0.009967219084501266,-0.07702022045850754,0.03977810963988304,0.019894897937774658,0.007566156797111034,0.0068940669298172,0.026631906628608704,-0.0029533053748309612,0.013546857982873917,0.05867700278759003,0.025152793154120445,-0.031898483633995056,0.08404641598463058,0.04668846353888512,0.06776806712150574,0.025047259405255318,0.09193958342075348,0.011493991129100323,0.048355113714933395,0.010111842304468155,0.06374797970056534,0.02343813329935074,0.05167319253087044,0.097781240940094,0.10418816655874252,0.037868380546569824,0.06821871548891068,0.09851626306772232,-0.00007495471800211817,0.13016292452812195,0.04227011650800705,-0.008864347822964191,0.02824683114886284,0.003569262335076928,-0.08665375411510468,0.03871336579322815,0.08389464020729065,-0.05376187711954117,0.08387405425310135,0.013851257041096687,0.15858764946460724,-0.02710866928100586,0.0027995752170681953,0.09128732979297638,0.05957929044961929,-0.1424720138311386,-0.0703510120511055,0.04910437762737274,-0.12895189225673676,-0.07116152346134186,0.020446769893169403,0.042544249445199966,-0.03476908057928085,0.0584842674434185,-0.050001371651887894,0.01770111545920372,0.009070176631212234,-0.0009298491640947759,0.03208348900079727,-0.03676662594079971,0.0009424614254385233,0.044585585594177246,-0.016688786447048187,0.07133917510509491,0.09124172478914261,-0.04954340308904648,-0.08433737605810165,-0.08760296553373337,0.11361683905124664,-0.02103111334145069,-0.05730235576629639,0.011301824823021889,-0.05600951239466667,0.03720192238688469,-0.1435549110174179,0.07378043979406357,0.10904103517532349,-0.09836570918560028,-0.011162123642861843,-0.0376305989921093,0.040717802941799164,-0.027654413133859634,0.02683384157717228,-0.049278728663921356,0.035354889929294586,-0.0027236908208578825,0.03642195835709572,-0.04181968420743942,0.060811810195446014,0.08137328922748566,-0.0994996428489685,0.03085624799132347,0.06213327497243881,-0.02157449908554554,-0.08293312788009644,0.05595751851797104,0.057741791009902954,-0.07581489533185959,-0.05696461722254753,-0.022243421524763107,-0.047629401087760925,-0.028158510103821754,-0.026719946414232254,-0.02703414112329483,0.055723484605550766,-0.08201965689659119,-0.01190393790602684,0.02330547757446766,0.02006986364722252,0.11464644968509674,0.00766860181465745,0.0738210529088974,-0.05795897915959358,-0.031170135363936424,0.08471105247735977,0.03173357993364334,0.09629449248313904,-0.016468748450279236,0.0436699241399765,-0.04392072558403015,-0.10188927501440048,0.025881754234433174,0.09526094049215317,0.08417254686355591,0.08643881231546402,0.029294898733496666,-0.07809276878833771,-0.055018287152051926,0.11050838977098465,0.017852619290351868,0.010020855814218521,0.028791753575205803,-0.11173868179321289,-0.02667585387825966,0.15913087129592896,-0.04863251373171806,0.0016447537345811725,0.0406239815056324,-0.03492271155118942,0.07956981658935547,0.10571463406085968,0.09797725826501846,0.034980643540620804,0.019388321787118912,0.0036869398318231106,-0.01102846022695303,0.0008645670022815466,-0.022856460884213448,0.02816871739923954,-0.16755086183547974,-0.09012039005756378,0.06952418386936188,0.0821269080042839,0.02372306026518345,-0.09182265400886536,-0.027557609602808952,-0.025013944134116173]},\"flagged_dissimilar_incidents\":null,\"incident_id\":333,\"nlp_similar_incidents\":[{\"incident_id\":20,\"similarity\":0.9987714886665344},{\"incident_id\":4,\"similarity\":0.9986178278923035},{\"incident_id\":52,\"similarity\":0.9986017942428589}],\"title\":\"Tesla on Autopilot Crashed Parked Michigan Police Car on Interstate\"}.\nIn field \"embedding\": In field \"__typename\": Unknown field.","locations":[{"line":1,"column":54}]}]}`

**Comment by lmcnulty** [comment] 2022-09-24 22:03
Ah, I see. For the incident edit form, that's actually fixed in [this PR](https://github.com/responsible-ai-collaborative/aiid/pull/1027/files#diff-10db02b7049c1f1226363baa99fd138def490052f0dd52f7e088281848599c62R54) but I can open another that makes just that change.

**Comment by smcgregor** [comment] 2022-09-24 22:45
I don't know when #1150 is scheduled to land, so it may need to be carved off.

**Comment by smcgregor** [comment] 2022-09-24 22:46
I just got to your MR in my email. Merged!

**Closed** 2022-09-24 22:45 UTC
Labels: Type:Bug, Effort: Low, current backlog, Priority:Critical
