### ISSUE TITLE
Incident History – Issue reports "Back to ... " button broken; NaN incident

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2355] opened 2023-10-16 20:41 UTC
Courtesy Danny:

>On issue reports, in the full history page, if you click "Back to Report #," it says, "Incident NaN not found"

This can be reproduced with an issue report's history page:
https://incidentdatabase.ai/cite/history/?report_number=3218&incident_id=null

When clicking "Back to Report 3218", the constructed link points to a NaN incident:
https://incidentdatabase.ai/cite/NaN/#r3218

@pdcp1 I believe you're familiar with this logic most recently, would you please take a look at the next chance?

**Comment by pdcp1** [comment] 2023-10-16 22:50
I found that the issue is with all `Issue Reports` (not happening with `Incident Reports`). I will work on a fix

**Comment by pdcp1** [comment] 2023-10-17 19:52
Closing this since it was already merged into Staging

**Closed by pdcp1** 2023-10-17 19:52 UTC
Labels: Type:Bug
