### ISSUE TITLE
Submission bug?

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#2132] opened 2023-06-30 02:34 UTC
Could not submit the article <https://www.theverge.com/2020/8/18/21373316/nypd-facial-recognition-black-lives-matter-activist-derrick-ingram> Pop-up message `Was not able to create the report, please review the form and try again.` was not helpful.

**Comment by smcgregor** [comment] 2023-06-30 13:20
"submit" means submitting the submit form or fetching the content?

**Comment by smcgregor** [comment] 2023-06-30 18:24
Only this link, or all of them? One particular link should not cause this problem.

**Comment by LKchemposer** [comment] 2023-06-30 18:25
I don't know of others, but this link ran into this problem.

**Comment by Janetbananet** [comment] 2023-07-21 20:05
@LKchemposer Are you still experiencing this bug?

**Comment by pdcp1** [comment] 2023-09-11 14:50
I am closing this since it cannot be reproduced anymore. Many changes to the submission form have been made since this was reported.

**Closed by pdcp1** 2023-09-11 14:50 UTC
