### ISSUE TITLE
Production Minified React Error

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1512] opened 2022-12-24 01:52 UTC
Production has a series of what are likely hydration errors. The app behaves fine, but this has been popping up periodically for a while and we need to take care of it.

`react-dom.production.min.js:131 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

**Comment by smcgregor** [comment] 2023-01-09 20:06
Every time I see this in the console I die a little inside. @lmcnulty @cesarvarela @pdcp1 @clari182 can any of you claim this one?

**Comment by pdcp1** [comment] 2023-01-10 15:14
The problem is with the Dates that are formatted directly on the JSX code.
The explained issue: https://github.com/vercel/next.js/discussions/38263
Solution: Use `useEffect` to format dates https://stackoverflow.com/questions/73005663/next-js-new-date-constructor-throwing-console-errors

We have to avoid using the `date-fns` `format` function directly on the JSX code. Use it inside of a `useEffect` instead.

**Comment by pdcp1** [comment] 2023-01-10 15:27
This issue was present in these components:
- `/components/blog/PostPreview.js`
- `/components/landing/LatestIncidentReport.js`
- `/templates/post.js`

**Comment by smcgregor** [comment] 2023-02-06 18:54
Reopening this since it appeared again.

**Comment by cesarvarela** [comment] 2023-03-10 01:05
It is mostly fixed, and there are a couple of tests alongside React being more strict this time; we can close this one for good.

**Closed by cesarvarela** 2023-03-10 01:05 UTC
Labels: Type:Bug, Priority:High
