### ISSUE TITLE
Weirdness on Bullets

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1358] opened 2022-11-08 19:23 UTC
https://staging-aiid.netlify.app/about

<img width="365" alt="Screen Shot 2022-11-08 at 11 23 02 AM" src="https://user-images.githubusercontent.com/64780/200656195-32c4edcc-d09f-49f6-a83b-de6ceaf0799e.png">

**Comment by lmcnulty** [comment] 2022-11-08 20:18
This is a duplicate of #1326.

**Closed by lmcnulty** 2022-11-08 20:18 UTC
Labels: Type:Bug, Effort: Low, current backlog
