### ISSUE TITLE
Report submission not working?

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#908] opened 2022-08-06 07:25 UTC
Report was not submitted despite all the fields being filled in, returning the error:

> Was not able to create the report, please review the form and try again.

![Screen Shot 2022-08-06 at 2 23 59 PM](https://user-images.githubusercontent.com/39468345/183239171-39f8e8b7-db85-4783-9db1-41ce3dee0f22.png)

**Comment by smcgregor** [comment] 2022-08-06 15:21
I was able to submit two different reports without any user apparent issue, but there was an error in the semantic relationship API, see below. Can you try submitting again to see if it recurs? 

<img width="497" alt="Screen Shot 2022-08-06 at 8 19 53 AM" src="https://user-images.githubusercontent.com/64780/183255273-3de3d66c-3b27-4f2b-852f-88d8a850c48d.png">

**Comment by smcgregor** [comment] 2022-08-06 15:25
The semanticallyRelated issue may have been a cold start issue since after a few tries, it started working.

**Comment by LKchemposer** [comment] 2022-08-09 07:01
It turned out that the Related feature was what caused the error. Without marking the incidents as related and leaving them as `?`, I did not run into the error.

**Comment by cesarvarela** [comment] 2022-08-09 17:44
assigning this to Luna since she's already working on it

**Comment by lmcnulty** [comment] 2022-08-15 18:03
This doesn't seem to be occurring anymore, although I don't know why. I'm leaving this open for now in case it shows up again and we can determine the cause.

**Comment by LKchemposer** [comment] 2022-08-17 08:42
It showed up again! This is what I gathered:

When an incident id was assigned, the pop-up asking about whether the to-be-submitted report is related to the report of that incident id showed up:

<img width="1203" alt="Screen Shot 2022-08-17 at 3 34 04 PM" src="https://user-images.githubusercontent.com/39468345/185073981-2e9e0877-e9f4-4056-981a-e42afdc8f22d.png">

But if the reports are marked as "related" or "unrelated," the to-be-submitted report cannot be submitted:

<img width="1203" alt="Screen Shot 2022-08-17 at 3 34 16 PM" src="https://user-images.githubusercontent.com/39468345/185074189-4f9b8908-aa49-46f0-8993-b7e64afa12ed.png">

But when the reports are left as ?, regardless of the other reports in other pop-ups (e.g., same-incident-date pop-up, same-author pop-up) being marked:

<img width="1203" alt="Screen Shot 2022-08-17 at 3 34 44 PM" src="https://user-images.githubusercontent.com/39468345/185074636-77325c5c-d8d7-48e9-b664-c543f5840684.png">

The to-be-submitted report can now be submitted:

<img width="1203" alt="Screen Shot 2022-08-17 at 3 35 02 PM" src="https://user-images.githubusercontent.com/39468345/185074712-c8a9d35f-515d-4302-b45d-882ecaf9557a.png">

**Conclusion:** It seems to be the case that the cause of the issue is with the same-incident-id pop-up

**Comment by lmcnulty** [comment] 2022-08-17 14:51
Ah, got it. The similarity selector for the incident ID is not supposed to be there at all, and it will be removed when #894 merges.

**Closed** 2022-08-22 15:46 UTC
Labels: PR:Needs Review
