### ISSUE TITLE
Add FB and LinkedIn social media logos to https://incidentdatabase.ai/

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#796] opened 2022-07-12 22:26 UTC
FB link to https://www.facebook.com/IncidentsDB/
LinkedIn link to https://www.linkedin.com/company/responsible-ai-collaborative

**Comment by clari182** [comment] 2023-01-25 14:26
Closing because duplicate of #1492

**Closed by clari182** 2023-01-25 14:26 UTC
