### ISSUE TITLE
Add `date_created` fields/data to subscriptions and notifications collections

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2511] opened 2023-12-21 16:12 UTC
This would help with issues like https://github.com/responsible-ai-collaborative/aiid/issues/2404.

(Notifications do have a `sentDate` field.)

**Comment by clari182** [comment] 2023-12-22 11:22
@cesarvarela @pdcp1 @kepae regarding this, I think it's a duplicate of #2387 
I've been working on this and the easiest solution is to create a trigger for each DB and it adds a created_at field on each entry.
I know there are some issues with triggers but I've been testing on my environment and it has been working for a week or so now.
Do you guys agree it's a good option?
Otherwise we would need to update the code and add that field manually on each insert and it's not that scalable.

**Comment by pdcp1** [comment] 2023-12-22 19:09
@clari182 As far as I remember, when restoring a DB version, all `on update` and `on insert` triggers must be manually reactivated on Atlas.

<img width="1566" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/d5bf0353-1c75-44be-9aa4-f79ab77c4fd5">

I don't expect any issues in Production as we don't restore Prod DB. This problem is occurring in individual environments and Staging.

@cesarvarela do you remember any other problem using triggers?

**Comment by cesarvarela** [comment] 2023-12-22 22:52
I think that's the main problem. They will crash when running a migration, but since this isn't a critical functionality, let's go with triggers.

**Comment by kepae** [comment] 2024-01-05 02:17
Thanks @clari182 -- I agree that this is a duplicate. We should go with the triggers because as César says, it's not critical functionality and it's low(er) effort to do triggers. If it ends up not working/proving buggy in the future, we can work around that.

**Comment by clari182** [comment] 2024-01-08 19:33
@cesarvarela @pdcp1 it looks like they don't crash if you create them from the data service (Data services > Triggers) instead of from Realm. The issue there is that the code of the triggers (1 for each db) would need to be added manually when setting up the project. From realm they're in the code.

What is the best option?
1. Having the triggers crash but have their code in the code 
2. Having the triggers not crash but having their code in the README to add manually

**Comment by pdcp1** [comment] 2024-01-12 13:08
@clari182 @cesarvarela I prefer option 1, keeping the trigger code versioned in the repo, to make the site deployment easier for new contributors and track code changes.

Regarding the trigger crashes, as far as I know, it doesn't happen on Production since we don't restore the Production database. Correct me if I'm wrong.
It happens on Staging and in our environments (when we restore Prod DB into each environment). That is not too often and eventually, we can restart the triggers manually after receiving the Realm alert notification.

**Comment by clari182** [comment] 2024-01-15 13:19
Yes, that makes sense!

**Comment by cesarvarela** [comment] 2024-01-15 15:05
Yup, keep as much into code as possible.

**Closed** 2024-01-25 12:22 UTC
Labels: Type: Enhancement
