### ISSUE TITLE
Menu highlight doesn't work in Spanish

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1128] opened 2022-09-20 23:01 UTC
:)

![image](https://user-images.githubusercontent.com/1172479/191379666-e9edc2e2-07e2-4e2a-a3ed-3e32e1c512c4.png)

:(

![image](https://user-images.githubusercontent.com/1172479/191379697-8465cb93-ecc5-49e1-9892-289e683e24ef.png)

**Comment by cesarvarela** [comment] 2022-09-20 23:05
![image](https://user-images.githubusercontent.com/1172479/191380089-177952de-562f-4d2b-b2cb-8612d867dfaf.png)

**Comment by smcgregor** [comment] 2022-09-20 23:25
Esto es extraño ;)

**Comment by pdcp1** [comment] 2022-09-30 20:06
Closing this since it cannot be reproduced on Prod https://incidentdatabase.ai/es/ (Chrome and Safari)

**Comment by cesarvarela** [comment] 2022-10-06 22:01
@pdcp1, you are looking at it wrong it doesn't work, it should show the current page, but it only works for english

**Comment by pdcp1** [comment] 2022-10-11 16:42
@cesarvarela this PR #1245 fixes the issue. The problem was that the active item doesn't localize the URL to compare. I also added some tests.

**Comment by pdcp1** [comment] 2022-10-14 22:59
Closing this since it was merged into Staging.

**Closed by pdcp1** 2022-10-14 22:59 UTC
Labels: PR:Needs Review, Stack:Front End
