### ISSUE TITLE
Spanish and French landing pages have placeholder translation text for recent reports

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#2701] opened 2024-03-19 21:48 UTC
Currently on prod.

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/c0eb6bbe-90f0-4226-8f76-b60e3add3880)

This also happens on discover, but it's less visible since the untranslated reports are not visible in the default state:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/95b31348-495d-47bb-9788-a268aabb7fcf)

**Comment by kepae** [comment] 2024-03-21 17:45
We are currently dry running the translation logic since moving to github actions for deploying.
Specifically, `TRANSLATE_DRY_RUN` defaults to `false` and is currently unset.

We will have to re-enable the translation, delete the placeholder translations, and re-run the translation.

Perhaps we can start by resuming translations, then drafting a migration that deletes report translations that contain exactly the placeholder text.

**Comment by pdcp1** [comment] 2024-04-29 21:37
@kepae @cesarvarela We still have reports with the translation placeholder `translated-` in Production. e.g: https://incidentdatabase.ai/ja/apps/discover/?is_incident_report=true&sortBy=submitted-date-desc

At the moment we have:
🇯🇵 86 records in `reports_ja`
🇪🇸 86 reports in `reports_es`
🇫🇷 86 records in `reports_fr`
🇺🇸 0 records in `reports_en`

We need to re-run the script since all records are from April 18, 2024, or later.

**Comment by kepae** [comment] 2024-04-29 22:16
Agh. I had misconfigured an env variable. `TRANSLATE_DRY_RUN=true` was in production still. I just switched that to false.

I'll copy the migration script and invoke it in another PR. Thanks for catching this.

**Comment by kepae** [comment] 2024-07-03 15:43
New reports are still not getting translated, despite having re-configured the dry run variables.

Let's re-address this when the build is proceeding normally again @cesarvarela.

**Comment by pdcp1** [comment] 2024-11-13 14:57
I found the reason for these translation placeholders.

### Explanation
As part of the build workflow in Production, we execute the `Build using Netlify` step twice.
- In the `Build site for testing` job
<img width="231" alt="image" src="https://github.com/user-attachments/assets/293646cb-4bed-4294-9b62-b105cf4abdc9">

- In the `netlify-deploy` job
<img width="158" alt="image" src="https://github.com/user-attachments/assets/54d58e30-c351-4a83-bef9-8571587d29f7">

The issue is that the first job, labeled `Build site for testing`, **does not include** the `TRANSLATE_DRY_RUN` environment variable. Code reference: https://github.com/responsible-ai-collaborative/aiid/blob/b7150d2127926c8aa74a283c6e1b2aeac991208f/.github/workflows/test-build.yml#L75
As a result, it performs the translation in dry run mode, adding the `translated-xx` prefix to all pending translations.
When the second job, `netlify-deploy`, begins, there are no translations left to process.

### Solution

- Don't run the translation process twice and use the `TRANSLATE_DRY_RUN` env variable.
  - It is already fixed as part of https://github.com/responsible-ai-collaborative/aiid/pull/3201

**Comment by kepae** [comment] 2024-11-13 18:38
HA, wonderful. Thanks Pablo. It was a workflow logic error, not a script error. This will be solved by re-factoring this out of the deployment workflow, as you suggest.

**Comment by cesarvarela** [comment] 2024-11-13 18:48
Ha, nice! (that workflow will be gone once we remove Cypress)

**Comment by pdcp1** [comment] 2024-11-13 19:07
> HA, wonderful. Thanks Pablo. It was a workflow logic error, not a script error. This will be solved by re-factoring this out of the deployment workflow, as you suggest.

Indeed, that's the good news 👍

**Comment by kepae** [comment] 2024-11-13 19:08
On that note, to reduce the cost of the first batch of translations, I've set `TRANSLATE_SUBMISSION_DATE_START` to
 `2024-09-01`.

**Comment by kepae** [comment] 2024-11-13 20:03
About older reports with no translations: let's backfill those over time, once we have the new workflow working on the latest reports.

About the migration: we've done this before, it can be repeated from: https://github.com/responsible-ai-collaborative/aiid/blob/4b5603012c380a6beac122717d4b6b48b2df5218/site/gatsby-site/migrations/2024.04.16T20.04.34.delete-dummy-translations.js

**Comment by pdcp1** [comment] 2024-12-03 22:26
A code refactor and fix for this was released as part of
- https://github.com/responsible-ai-collaborative/aiid/pull/3249

The translation process was completed successfully.
Details: https://github.com/responsible-ai-collaborative/aiid/actions/runs/12148973057/job/33878642702

**Comment by pdcp1** [comment] 2024-12-03 23:50
Fixed 🎉 
- https://incidentdatabase.ai/es
- https://incidentdatabase.ai/fr
- https://incidentdatabase.ai/ja
<img width="1785" alt="image" src="https://github.com/user-attachments/assets/c17992c4-88b2-49f6-9039-f718dcea20dc">

**Closed by pdcp1** 2024-12-03 23:50 UTC
Labels: Type: Bug, Priority: High

**Comment by kepae** [comment] 2024-12-03 23:55
🎊
